export const environment = {
  production: true,
  showDebugginLogs: false,
  sourceUrl: "https://tap.evryka.org",
  baseUrl: "https://tap.evryka.org/",
  apiUrl: "https://api.evryka.org/api/",
  wsBase: 'https://api.evryka.org/',
  wsPath: 'socket.io',
  SOCKET_ENDPOINT: 'https://api.evryka.org/',
  PYTHON_SOCKET_ENDPOINT: 'https://tap.evryka.org/ai/',
  VideoEndpoint: 'http://localhost:5000/api',
  //apiUrl: "https://localhost:3000/api/",
  //SOCKET_ENDPOINT: 'https://localhost:3000' 
  RECAPTCHA_KEY_V3: '6LfoX88jAAAAABh2BwECgqA5bhBWZVbCaUy1rWZN',
  RECAPTCHA_KEY_V2: '6LdZcc8jAAAAAHpdUTkSffrpinj8uEWXVxWfOR-V',

  // Real values for this block are injected at build time (see .github/workflows/deploy.yml)
  // and are never committed. For local dev, fill these in on your machine without committing them.
  socialLogin: {
    GOOGLE: {
      CLIENT_SECRET: '__GOOGLE_CLIENT_SECRET__',
      CLIENT_ID: '__GOOGLE_CLIENT_ID__',
      API_KEY: '__GOOGLE_API_KEY__',
      CUSTOMER_ID: 'C01jxunqz',
      EMAIL: 'admin@evryka.org'
    },
    FACEBOOK_CLIENT_ID: '__FACEBOOK_CLIENT_ID__',
    LINKEDIN: {
      CLIENT_ID: '__LINKEDIN_CLIENT_ID__',
      CLIENT_SECRET: '__LINKEDIN_CLIENT_SECRET__'
    },
    TELEGRAM: {
      LINK: 'https://t.me/',
      BOT_NAME: 'Evryka_Bot'
    }
  },
  analytics: {
    POSTHOG_ID: 57441,
    POSTHOG_KEY: '__POSTHOG_KEY__',
    POSTHOG_HOST: "https://eu.i.posthog.com",
    HOTJAR_ID: 5339584
  },
  storage: {
    currentUser: 'local-evryka-current-user',
    userId: 'local-evryka-current-user-id',
    token: 'local-evryka-current-user-token',
    refreshToken: 'local-evryka-current-user-refresh-token',
    prefixToken: 'local-evryka-current-user-',
    tokenExpiresAt: 'local-evryka-current-user-token-expires_at',
    candidateProfileCache: 'local-talent-profile-cache'
  },
  externalPlatforms: {
    workable: {
      accessToken: '__WORKABLE_ACCESS_TOKEN__',
    }
  },
  serverPaths: {
    login: `auth/login`,
    register: 'auth/register',
    recover: 'auth/recover',
    refresh: 'auth/refresh',
    authGoogle: 'auth/google',
    authLinkedIn: 'auth/linkedin',
    postLinkedInArticle: 'publish-linkedin',
    linkedInBlogs: 'linkedin-blogs',

    accessTypes: `access-types`,
    functionalBlocks: `functional-blocks`,
    roles: `roles`,
    permissions: `permissions`,
    visitorPath: "visitors",
    ipExceptionsPath: "ip-exceptions",
    positionPath: "positions",
    positions: "positions",
    certifications: "professional-certifications",
    education: "education",
    companiesVersions: "companies-versions",
    companiesVerfied: "companies-verfied",
    companyValues: "company-values",
    companyBenefits: "company-benefits",
    currentCompany: "current-company",
    industryDomains: 'industry-domains',
    industrySubgroups: 'industry-subgroups',
    benefits: "position-benefits",
    countries: "countries",
    cities: "cities",
    blogs: "blogs",
    blogImages: "blog-images",
    briefs: "briefs",
    briefTemplates: "brief-templates",
    briefQuestions: "brief-questions",
    briefSections: "brief-sections",
    customerBrief: "customer-brief",
    leads: "leads",
    userProfiles: "user-profiles",
    userCredentials: "user-credentials",
    candidateProfile: "talent-profile",
    usersPath: "users",
    cvs: "cvs",
    cvPdf: "cv-pdf",
    visitCardsPdf: "visit-cards-pdf",
    meetings: "meetings",
    meetingInvitations: "meeting-invitations",
    meetingTemplates: "meeting-templates",
    schedule: "schedule",
    scheduleSettings: "schedule-default-settings",
    currencies: "currencies",
    motivationalFactors: "motivational-factors",
    coverLetters: "cover-letters",
    profilePhotoPath: "profile-photos",
    changePassword: "change-password",
    socialMedia: "social-media",
    recruitmentPlatform: "recruitment-platforms",
    userRecruitmentPlatform: "user-recruitment-platforms",
    verifiedPositions: "verified-positions",
    universities: "universities",
    skills: "skills",
    presentationPdf: "presentation-content",
    emailVerification: "verification-requests",
    sessionTokens: "session-tokens",
    positionsLiked: "positions-liked",
    positionBenefits: "position-benefits",
    positionPipeline: "position-pipelines",
    pipelineStage: "pipeline-stages",
    talentPipelineProgress: "talent-pipeline-progress",
    pipelineStageFeedbacks: "pipeline-stage-feedbacks",
    positionWorkflow: "position-workflow",
    positionWorkflowStage: "position-workflow-stage",
    like: "like",
    unlike: "unlike",
    blogsFavorite: "blogs-favorite",
    favoriteBlog: "favorite",
    unfavoriteBlog: "unfavorite",
    blogPostComments: "blog-post-comments",
    sessionTokensPaths: {
      linkedIn: 'linkedin',
    },
    chatGpt: "chat-gpt",
    generateContent: "generate-content",
    generateOpenPosition: "generate-open-position",
    linkedInRecruitmentPlatform: "linked-in-recruitment-platforms",
    chatRoom: "chat-rooms",
    chatMessage: "chat-messages",
    videoChatRoom: "video-chat-rooms",
    videoChatRoomParticipant: "video-room-participants",
    screeningForms: 'screening-forms',
    screeningQuestions: 'screening-questions',
    screeningQuestionTemplates: 'screening-question-templates',
    screeningResponses: 'screening-responses',
    videoRecordings: 'video-records',
    telegramNotifications: 'telegram-notifications',
    whatsapp: 'whatsapp',
    talentNotes: 'talent-notes',
    liveCodingSessions: 'live-coding-sessions',
    codeSnippets: 'code-snippets',
    recruiterActivityAccess: 'recruiter-activity-access',
  },
  routes: {
    main: 'main',
    authentication: 'auth',
    services: 'services',
    servicesPresentation: 'services/presentation',
    demo: 'demo',
    contactUs: 'contact-us',
    scheduleDemo: 'schedule/demo',
    user: 'user',
    auth: {
      login: `auth/login`,
      signup: 'auth/signup',
      register: 'auth/register',
      registration: 'auth/registration',
      passwordRecovery: 'auth/password-recovery',
      emailVerification: 'verification-id',
      phoneVerification: 'auth/phone-verification',
      verifyIdentity: 'auth/verify-identity',
    },
    screening: 'screening',
    assessment: 'assessment',
    schedule: {
      schedule: "schedule",
      scheduleCalendar: "calendar",
      scheduleSchedule: "schedule",
      scheduleSettings: "settings",
      calendarBookMeeting: "calendar/book-meeting",
      bookMeeting: "book-meeting",
    },
    saved: {
      saved: "saved",
      savedPositions: "saved-positions",
    },
    communication: {
      communication: "communication",
      interviews: "interviews",
      textChat: "text-chat",
      videoChat: "video-chat",
      room: "room",
      videoInterview: "video-interview",
    },
    admin: 'admin',
    adminTab: {
      profile: 'profile',
      brief: {
        brief: 'brief',
        adminBrief: 'admin/brief',
        adminBriefBlock: 'admin/brief/b-block',
        templates: "templates",
        sections: "sections",
        questions: "questions",

        briefBlock: "b-block",

        briefDashboard: "dashboard",
        briefTemplates: "templates",
        briefSections: "sections",
        briefQuestions: "questions",
        briefAnswers: "answers",

        adminBriefDashboard: "admin/brief/dashboard",
        adminBriefQuestions: "admin/brief/questions",
        adminBriefSections: "admin/brief/sections",
        adminBriefTemplates: "admin/brief/templates",
        adminBriefAnswers: "admin/brief/answers",

        adminBriefBlockDashboard: "admin/brief/b-block/dashboard",
        adminBriefBlockQuestions: "admin/brief/b-block/questions",
        adminBriefBlockSections: "admin/brief/b-block/sections",
        adminBriefBlockTemplates: "admin/brief/b-block/templates",
        adminBriefBlockAnswers: "admin/brief/b-block/answers"
      },
      companies: {
        companies: 'companies',
        adminCompanies: 'admin/companies',
        adminCompaniesBlock: 'admin/companies/c-block',

        companiesBlock: "c-block",

        briefDashboard: "dashboard",
        briefTemplates: "list",

        adminCompaniesDashboard: "admin/companies/dashboard",
        adminCompaniesList: "admin/companies/list",

        adminCompaniesBlockDashboard: "admin/companies/c-block/dashboard",
        adminCompaniesBlockList: "admin/companies/c-block/list",
      },
      users: {
        users: "users",
        adminUsers: 'admin/users',
        usersBlock: "u-block",
        adminUsersBlock: "admin/users/u-block"
      },
      universities: {
        universities: "universities",
        adminUniversities: 'admin/universities',
        universitiesBlock: "un-block",
        adminUniversitiesBlock: "admin/universities/un-block"
      },
      skills: {
        skills: "skills",
        adminSkills: 'admin/skills',
        skillsBlock: "s-block",
        adminSkillsBlock: "admin/skills/s-block"
      },
      recruitmentPlatforms: {
        recruitmentPlatforms: "recruitment-platforms",
        adminRecruitmentPlatforms: 'admin/recruitment-platforms',
        recruitmentPlatformsBlock: "rp-block",
        adminRecruitmentPlatformsBlock: "admin/recruitment-platforms/rp-block"
      },
      screeningQuestionnaires: {
        screeningQuestionnaires: "screening-questionnaires",
        adminScreeningQuestionnaires: 'admin/screening-questionnaires',
        screeningQuestionnairesBlock: "sq-block",
        adminScreeningQuestionnairesBlock: "admin/screening-questionnaires/sq-block"
      },
      positionBenefits: {
        positionBenefits: "position-benefits",
        adminPositionBenefits: 'admin/position-benefits',
        positionBenefitsBlock: "pb-block",
        adminPositionBenefitsBlock: "admin/position-benefits/pb-block"
      },
      motivationalFactors: {
        motivationalFactors: "motivational-factors",
        adminMotivationalFactors: 'admin/motivational-factors',
        motivationalFactorsBlock: "mf-block",
        adminMotivationalFactorsBlock: "admin/motivational-factors/mf-block"
      },
      socialMedia: {
        social: "social",
        media: "media",
        adminSocialMedia: 'admin/social/media',
        adminSocialMediaBlock: "admin/social/media",
      },
      permissions: {
        permissions: "permissions",
        adminPermissions: 'admin/permissions',
        permissionsBlock: "p-block",
        adminPermissionsBlock: "admin/permissions/p-block",
        permissionsList: "list",
        rolesList: "roles",
        accessTypes: "access-types",
        functionalBlocks: "functional-blocks",
        adminPermissionsList: "admin/permissions/p-block/list",
        adminRolesList: 'admin/permissions/p-block/roles',
        adminAccessTypes: 'admin/permissions/p-block/access-types',
        adminFunctionalBlocks: 'admin/permissions/p-block/functional-blocks',
      },
      visitors: {
        visitors: "visitors",
        adminVisitors: 'admin/visitors',
        visitorsBlock: "v-block",
        adminVisitorsBlock: "admin/visitors/v-block",
        visitorsList: 'list',
        ipExceptions: "ip-exclusions",
        charts: "charts",
        adminVisitorsList: "admin/visitors/v-block/list",
        adminVisitorsIpExceptions: "admin/visitors/v-block/ip-exclusions",
        adminVisitorsCharts: "admin/visitors/v-block/charts"
      },
      schedule: {
        schedule: "schedule",
        adminSchedule: "admin/schedule",
        adminScheduleCalendar: "admin/schedule/calendar",
        adminScheduleCalendarAvailability: "admin/schedule/calendar/availability",
        calendarAvailability: "calendar/availability",

        scheduleCalendar: "calendar",
        scheduleSchedule: "schedule",
        scheduleSettings: "settings",
        calendarBookMeeting: "calendar/book-meeting",
        bookMeeting: "book-meeting",

        adminScheduleBlockCalendar: "admin/schedule/calendar",
        adminScheduleBlockSchedule: "admin/schedule/schedule",
        adminScheduleBlockSettings: "admin/schedule/settings",
      },
      communication: {
        communication: "communication",
        interviews: "interviews",
        textChat: "text-chat",
        videoChat: "video-chat",
        videoInterview: "video-interview",
        adminCommunicationInterviews: "admin/communication/interviews",
        adminCommunicationTextChat: "admin/communication/text-chat",
        adminCommunicationVideoChat: "admin/communication/video-chat",
      },
      blogs: {
        blogs: "blog",
        posts: "posts",
        adminBlogs: "admin/blog/posts"
      },
      positionsAdmin: "positions-block",
      career: 'career',
      dashboard: {
        dashboard: "dashboard",
        adminDashboard: 'admin/dashboard',
        dashboardBlock: "d-block",
        adminDashboardBlock: "talent/dashboard/d-block"
      },
      socialMediaAdmin: "social/media",
      blogsAdmin: 'blog',
      postsAdmin: 'posts',
    },
    recruitment: 'recruitment',
    recruitmentTab: {
      profile: 'profile',
      positionManagement: {
        positionManagement: "position-management",
        recruitmentPositionManagement: 'recruitment/position-management',
        positionManagementBlock: "pm-block",
        recruitmentPositionManagementBlock: "recruitment/position-management/pm-block"
      },
      dashboard: {
        dashboard: "dashboard",
        recruitmentDashboard: 'recruitment/dashboard',
        dashboardBlock: "d-block",
        recruitmentDashboardBlock: "recruitment/dashboard/d-block"
      },
      companyManagement: {
        companyManagement: "company-management",
        recruitmentCompanyManagement: 'recruitment/company-management',
        companyManagementBlock: "cm-block",
        recruitmentCompanyManagementBlock: "recruitment/company-management/cm-block"
      },
      liveCoding: {
        liveCoding: "live-coding",
        recruitmentLiveCoding: 'recruitment/live-coding',
        liveCodingBlock: "lc-block",
        recruitmentLiveCodingBlock: "recruitment/live-coding/lc-block",
        liveCodingPersonal: "personal/:userId",
        recruitmentLiveCodingPersonal: "recruitment/live-coding/personal/:userId",
        recruitmentLiveCodingPersonalBlock: "recruitment/live-coding/personal",
        liveCodingInterview: "interview/:roomId",
        recruitmentLiveCodingInterview: "recruitment/live-coding/interview/:roomId",
      },
      communication: {
        communication: "communication",
        interviews: "interviews",
        textChat: "text-chat",
        videoChat: "video-chat",
        videoInterview: "video-interview",
        recruitmentCommunicationInterviews: "recruitment/communication/interviews",
        recruitmentCommunicationTextChat: "recruitment/communication/text-chat",
        recruitmentCommunicationVideoChat: "recruitment/communication/video-chat",
      },
      schedule: {
        schedule: "schedule",
        recruitmentSchedule: "recruitment/schedule",
        recruitmentScheduleCalendar: "recruitment/schedule/calendar",
        recruitmentScheduleCalendarAvailability: "recruitment/schedule/calendar/availability",
        calendarAvailability: "calendar/availability",

        scheduleCalendar: "calendar",
        scheduleSchedule: "schedule",
        scheduleSettings: "settings",
        calendarBookMeeting: "calendar/book-meeting",
        bookMeeting: "book-meeting",

        recruitmentScheduleBlockCalendar: "recruitment/schedule/calendar",
        recruitmentScheduleBlockSchedule: "recruitment/schedule/schedule",
        recruitmentScheduleBlockSettings: "recruitment/schedule/settings",
      },
      pipelineBoard: {
        pipelineBoard: 'pipeline-board',
        recruitmentPipelineBoard: 'recruitment/pipeline-board',
        pipelineBoardBlock: "pb-block",
        recruitmentPipelineBoardBlock: "recruitment/pipeline-board/pb-block"
      },
      paymentMethods: {
        paymentMethods: "payment-methods",
        recruitmentPaymentMethods: 'recruitment/payment-methods',
        paymentMethodsBlock: "pay-block",
        recruitmentPaymentMethodsBlock: "recruitment/payment-methods/pay-block"
      },
      team: {
        team: "team",
        recruitmentTeam: "recruitment/team",
        teamBlock: "t-block",
        recruitmentTeamBlock: "recruitment/team/t-block",
        activityAccess: "activity-access",
        recruitmentTeamActivityAccess: "recruitment/team/t-block/activity-access",
      },
      saved: {
        saved: "saved",
        recruitmentSaved: 'recruitment/saved',
        savedBlock: "sv-block",
        recruitmentSavedBlock: "recruitment/saved/sv-block",
        savedPositions: "saved-positions",
        recruitmentSavedPositions: "recruitment/saved/saved-positions",
        recruitmentSavedPositionsBlock: "recruitment/saved/sv-block/saved-positions",
      },
    },
    talent: 'talent',
    publicProfile: 'public-profile',
    talentTab: {
      publicProfile: 'public-profile',
      profile: 'profile',
      calendar: 'calendar',
      expertise: {
        expertise: "expertise",
        talentExpertise: 'talent/expertise',
        expertiseBlock: "e-block",
        talentExpertiseBlock: "talent/expertise/e-block"
      },
      cvTempletes: {
        cvTempletes: "cv-templates",
        creativeBlocksTemplate: "creative-blocks",
        minimalistSingleTemplate: "minimalist-single",
        modernTwoColumnTemplate: "modern-two-column",
        timelineProfessionalTemplate: "timeline-professional",
        executiveInfographicTemplate: "executive-infographic",
        hexagonTechTemplate: "hexagon-tech",
        magazineEditorialTemplate: "magazine-editorial",
        splitAccentTemplate: "split-accent",
        talentCvTempletes: 'talent/cv-templates',
        talentCvTempletesMinimalistSingle: "talent/cv-templates/minimalist-single",
      },
      applicationManagement: {
        applicationManagement: "application-management",
        talentApplicationManagement: 'talent/application-management',
        applicationManagementBlock: "am-block",
        talentApplicationManagementBlock: "talent/application-management/am-block"
      },
      recommendationManagement: {
        recommendationManagement: "recommendation-management",
        talentRecommendationManagement: 'talent/recommendation-management',
        recommendationManagementBlock: "rm-block",
        talentRecommendationManagementBlock: "talent/recommendation-management/rm-block"
      },
      communication: {
        communication: "communication",
        interviews: "interviews",
        textChat: "text-chat",
        videoChat: "video-chat",
        videoInterview: "video-interview",
        communicationInterviews: "talent/communication/interviews",
        communicationTextChat: "talent/communication/text-chat",
        communicationVideoChat: "talent/communication/video-chat",
      },
      liveCoding: {
        liveCoding: "live-coding",
        talentLiveCoding: 'talent/live-coding',
        liveCodingBlock: "lc-block",
        talentLiveCodingBlock: "talent/live-coding/lc-block",
        liveCodingPersonal: "personal/:userId",
        talentLiveCodingPersonal: "talent/live-coding/personal/:userId",
        talentLiveCodingPersonalBlock: "talent/live-coding/personal",
        liveCodingInterview: "interview/:roomId",
        talentLiveCodingInterview: "talent/live-coding/interview/:roomId",
      },
      schedule: {
        schedule: "schedule",
        talentSchedule: "talent/schedule",
        talentScheduleCalendar: "talent/schedule/calendar",
        talentScheduleCalendarAvailability: "talent/schedule/calendar/availability",
        calendarAvailability: "calendar/availability",

        scheduleCalendar: "calendar",
        scheduleSchedule: "schedule",
        scheduleSettings: "settings",
        calendarBookMeeting: "calendar/book-meeting",
        bookMeeting: "book-meeting",

        talentScheduleBlockCalendar: "talent/schedule/calendar",
        talentScheduleBlockSchedule: "talent/schedule/schedule",
        talentScheduleBlockSettings: "talent/schedule/settings",
      },
      paymentMethods: {
        paymentMethods: "payment-methods",
        talentPaymentMethods: 'talent/payment-methods',
        paymentMethodsBlock: "pay-block",
        talentPaymentMethodsBlock: "talent/payment-methods/pay-block"
      },
      dashboard: {
        dashboard: "dashboard",
        talentDashboard: 'talent/dashboard',
        dashboardBlock: "d-block",
        talentDashboardBlock: "talent/dashboard/d-block"
      },
      saved: {
        saved: "saved",
        talentSaved: 'talent/saved',
        savedBlock: "sv-block",
        talentSavedBlock: "talent/saved/sv-block",
        savedPositions: "saved-positions",
        talentSavedPositions: "talent/saved/saved-positions",
        talentSavedPositionsBlock: "talent/saved/sv-block/saved-positions",
      },
    },
    interviewer: 'interviewer',
    interviewerTab: {
      profile: 'profile',
      dashboard: {
        dashboard: "dashboard",
        interviewerDashboard: 'interviewer/dashboard',
        dashboardBlock: "d-block",
        interviewerDashboardBlock: "interviewer/dashboard/d-block"
      },
      communication: {
        communication: "communication",
        interviews: "interviews",
        textChat: "text-chat",
        videoChat: "video-chat",
        videoInterview: "video-interview",
        communicationInterviews: "interviewer/communication/interviews",
        communicationTextChat: "interviewer/communication/text-chat",
        communicationVideoChat: "interviewer/communication/video-chat",
      },
      liveCoding: {
        liveCoding: "live-coding",
        interviewerLiveCoding: 'interviewer/live-coding',
        liveCodingBlock: "lc-block",
        interviewerLiveCodingBlock: "interviewer/live-coding/lc-block",
        liveCodingPersonal: "personal/:userId",
        interviewerLiveCodingPersonal: "interviewer/live-coding/personal/:userId",
        interviewerLiveCodingPersonalBlock: "interviewer/live-coding/personal",
        liveCodingInterview: "interview/:roomId",
        interviewerLiveCodingInterview: "interviewer/live-coding/interview/:roomId",
      },
      schedule: {
        schedule: "schedule",
        interviewerSchedule: "interviewer/schedule",
        interviewerScheduleCalendar: "interviewer/schedule/calendar",
        interviewerScheduleCalendarAvailability: "interviewer/schedule/calendar/availability",
        calendarAvailability: "calendar/availability",

        scheduleCalendar: "calendar",
        scheduleSchedule: "schedule",
        scheduleSettings: "settings",
        calendarBookMeeting: "calendar/book-meeting",
        bookMeeting: "book-meeting",

        interviewerScheduleBlockCalendar: "interviewer/schedule/calendar",
        interviewerScheduleBlockSchedule: "interviewer/schedule/schedule",
        interviewerScheduleBlockSettings: "interviewer/schedule/settings",
      },
      paymentMethods: {
        paymentMethods: "payment-methods",
        interviewerPaymentMethods: 'interviewer/payment-methods',
        paymentMethodsBlock: "pay-block",
        interviewerPaymentMethodsBlock: "interviewer/payment-methods/pay-block"
      },
    },
    userProfile: 'user/profile',
    positions: 'career/positions',
    screeningQuestionnaire: 'screening-questionnaire',
    liveCoding: 'live-coding',
    companies: 'career/companies',
    career: 'career',
    briefTemplates: 'brief/templates',
    templates: 'brief/templates',
    brief: "brief",
    briefForm: "form",
    blogs: "blog/posts",
    privacyPolicy: "privacy-policy",
    pricingPlans: "pricing-plans",
    subscription: "subscription",
  }
};