import { QuestionType } from "../../position-management/models/screening-question";
import { PositionTag, QuestionCategory, ScreeningQuestionTemplate, SeniorityLevel } from "../models/screening-question-templates";

export const SCREENING_QUESTION_TEMPLATES: ScreeningQuestionTemplate[] = [

  // ===== UNIVERSAL =====
  {
    text: 'Tell us about yourself and your professional background.',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: Object.values(SeniorityLevel),
    category: QuestionCategory.Motivation,
    durationInSeconds: 90,
  },
  {
    text: 'Why are you interested in this role?',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: Object.values(SeniorityLevel),
    category: QuestionCategory.Motivation,
    durationInSeconds: 90,
  },
  {
    text: 'What motivates you in your work?',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: Object.values(SeniorityLevel),
    category: QuestionCategory.CultureFit,
    durationInSeconds: 60,
  },
  {
    text: 'Tell us about a recent challenge you faced at work.',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: Object.values(PositionTag),
    seniorityLevels: Object.values(SeniorityLevel),
    category: QuestionCategory.ProblemSolving,
    durationInSeconds: 120,
  },

  // ===== FRONTEND / FULLSTACK =====
  {
    text: 'Explain a complex UI problem you solved recently.',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: [PositionTag.Frontend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Middle, SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Technical,
    durationInSeconds: 120,
  },
  {
    text: 'How do you ensure accessibility in your applications?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: [PositionTag.Frontend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Middle, SeniorityLevel.Senior],
    category: QuestionCategory.Technical,
    durationInSeconds: 90,
  },
  {
    text: 'How do you approach frontend performance optimization?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: [PositionTag.Frontend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Technical,
    durationInSeconds: 120,
  },

  // ===== BACKEND / FULLSTACK =====
  {
    text: 'Explain a backend system or API you designed.',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: [PositionTag.Backend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Middle, SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Technical,
    durationInSeconds: 120,
  },
  {
    text: 'Tell us about a scalability or performance issue you solved.',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: [PositionTag.Backend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Technical,
    durationInSeconds: 120,
  },
  {
    text: 'How do you ensure security in backend applications?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: [PositionTag.Backend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Technical,
    durationInSeconds: 90,
  },

  // ===== JUNIOR =====
  {
    text: 'What was the last technical topic you learned?',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Junior],
    category: QuestionCategory.ProblemSolving,
    durationInSeconds: 60,
  },
  {
    text: 'How do you approach tasks you do not fully understand yet?',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Junior],
    category: QuestionCategory.ProblemSolving,
    durationInSeconds: 60,
  },

  // ===== SENIOR / LEAD =====
  {
    text: 'How do you mentor or support less experienced teammates?',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Leadership,
    durationInSeconds: 120,
  },
  {
    text: 'How do you balance technical debt and delivery speed?',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Leadership,
    durationInSeconds: 120,
  },
  // ===== UNIVERSAL (NEW) =====
  {
    text: 'How do you usually plan your work when you have multiple tasks at once?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: Object.values(PositionTag),
    seniorityLevels: Object.values(SeniorityLevel),
    category: QuestionCategory.Communication,
    durationInSeconds: 60,
  },
  {
    text: 'Tell us about a time you had to adapt quickly to a change at work.',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: Object.values(PositionTag),
    seniorityLevels: Object.values(SeniorityLevel),
    category: QuestionCategory.ProblemSolving,
    durationInSeconds: 90,
  },
  {
    text: 'What kind of work environment helps you do your best work?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: Object.values(PositionTag),
    seniorityLevels: Object.values(SeniorityLevel),
    category: QuestionCategory.CultureFit,
    durationInSeconds: 60,
  },

  // ===== FRONTEND / FULLSTACK (NEW) =====
  {
    text: 'How do you approach maintaining consistency in large user interfaces?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: [PositionTag.Frontend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Middle, SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Technical,
    durationInSeconds: 90,
  },
  {
    text: 'Tell us about a time you had to refactor existing frontend code.',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: [PositionTag.Frontend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Middle, SeniorityLevel.Senior],
    category: QuestionCategory.Technical,
    durationInSeconds: 120,
  },

  // ===== BACKEND / FULLSTACK (NEW) =====
  {
    text: 'How do you decide when to introduce new technologies into a backend system?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: [PositionTag.Backend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Technical,
    durationInSeconds: 90,
  },
  {
    text: 'Tell us about a time you had to debug a hard-to-reproduce backend issue.',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: [PositionTag.Backend, PositionTag.Fullstack],
    seniorityLevels: [SeniorityLevel.Middle, SeniorityLevel.Senior],
    category: QuestionCategory.ProblemSolving,
    durationInSeconds: 120,
  },

  // ===== JUNIOR (NEW) =====
  {
    text: 'How do you usually prepare before starting a new task or feature?',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Junior],
    category: QuestionCategory.ProblemSolving,
    durationInSeconds: 60,
  },
  {
    text: 'Tell us about a time you received feedback that helped you improve.',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Junior],
    category: QuestionCategory.Communication,
    durationInSeconds: 60,
  },

  // ===== SENIOR / LEAD (NEW) =====
  {
    text: 'How do you take ownership of outcomes when things do not go as planned?',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Leadership,
    durationInSeconds: 90,
  },
  {
    text: 'Tell us about a time you had to influence a decision without direct authority.',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Leadership,
    durationInSeconds: 120,
  },
  {
    text: 'How do you ensure alignment within a team when priorities change?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Leadership,
    durationInSeconds: 90,
  },

  // ===== CROSS-FUNCTIONAL / COLLABORATION (NEW) =====
  {
    text: 'Tell us about a time you worked closely with non-technical stakeholders.',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Middle, SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Communication,
    durationInSeconds: 90,
  },
  {
    text: 'How do you explain complex technical topics to non-technical audiences?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: Object.values(PositionTag),
    seniorityLevels: [SeniorityLevel.Middle, SeniorityLevel.Senior, SeniorityLevel.Lead],
    category: QuestionCategory.Communication,
    durationInSeconds: 90,
  },
  {
    text: 'What helps you stay focused and productive during long or complex projects?',
    type: QuestionType.VideoResponse,
    required: false,
    positionTags: Object.values(PositionTag),
    seniorityLevels: Object.values(SeniorityLevel),
    category: QuestionCategory.CultureFit,
    durationInSeconds: 60,
  },
  {
    text: 'How do you usually monitor the health of production systems?',
    type: QuestionType.VideoResponse,
    required: true,
    positionTags: [PositionTag.DevOps],
    seniorityLevels: Object.values(SeniorityLevel),
    category: QuestionCategory.Technical,
  }, 
  {
  text: 'What is your experience with CI/CD pipelines?',
  type: QuestionType.VideoResponse,
  required: true,
  positionTags: [PositionTag.DevOps],
  seniorityLevels: Object.values(SeniorityLevel),
  category: QuestionCategory.Technical,
},
{
  text: 'Which cloud platforms have you worked with?',
  type: QuestionType.VideoResponse,
  required: true,
  positionTags: [PositionTag.DevOps],
  seniorityLevels: Object.values(SeniorityLevel),
  category: QuestionCategory.Technical,
},
{
  text: 'Describe a production incident you handled and what you learned from it.',
  type: QuestionType.VideoResponse,
  required: true,
  positionTags: [PositionTag.DevOps],
  seniorityLevels: [
    SeniorityLevel.Middle,
    SeniorityLevel.Senior,
    SeniorityLevel.Lead,
  ],
  category: QuestionCategory.ProblemSolving,
},
{
  text: 'How do you usually respond when a critical system goes down?',
  type: QuestionType.VideoResponse,
  required: false,
  positionTags: [PositionTag.DevOps],
  seniorityLevels: Object.values(SeniorityLevel),
  category: QuestionCategory.ProblemSolving,
  durationInSeconds: 90,
},
{
  text: 'How do you balance speed of delivery with system stability?',
  type: QuestionType.VideoResponse,
  required: false,
  positionTags: [PositionTag.DevOps],
  seniorityLevels: [
    SeniorityLevel.Senior,
    SeniorityLevel.Lead,
  ],
  category: QuestionCategory.Leadership,
  durationInSeconds: 60,
},
{
  text: 'How do you help development teams adopt DevOps best practices?',
  type: QuestionType.VideoResponse,
  required: false,
  positionTags: [PositionTag.DevOps],
  seniorityLevels: [
    SeniorityLevel.Senior,
    SeniorityLevel.Lead,
  ],
  category: QuestionCategory.Leadership,
},
{
  text: 'What is your approach to testing a new feature?',
  type: QuestionType.VideoResponse,
  required: true,
  positionTags: [PositionTag.QA],
  seniorityLevels: Object.values(SeniorityLevel),
  category: QuestionCategory.Technical,
},
{
  text: 'What types of testing have you worked with?',
  type: QuestionType.VideoResponse,
  required: true,
  positionTags: [PositionTag.QA],
  seniorityLevels: Object.values(SeniorityLevel),
  category: QuestionCategory.Technical,
},
{
  text: 'How do you decide what should be tested first?',
  type: QuestionType.VideoResponse,
  required: true,
  positionTags: [PositionTag.QA],
  seniorityLevels: Object.values(SeniorityLevel),
  category: QuestionCategory.ProblemSolving,
},
{
  text: 'How do you usually report a bug to developers?',
  type: QuestionType.VideoResponse,
  required: true,
  positionTags: [PositionTag.QA],
  seniorityLevels: Object.values(SeniorityLevel),
  category: QuestionCategory.Communication,
},
{
  text: 'Describe a difficult bug you found and how you identified it.',
  type: QuestionType.VideoResponse,
  required: false,
  positionTags: [PositionTag.QA],
  seniorityLevels: [
    SeniorityLevel.Middle,
    SeniorityLevel.Senior,
    SeniorityLevel.Lead,
  ],
  category: QuestionCategory.ProblemSolving,
  durationInSeconds: 90,
},
{
  text: 'Do you have experience with test automation? If yes, which tools?',
  type: QuestionType.VideoResponse,
  required: false,
  positionTags: [PositionTag.QA],
  seniorityLevels: [
    SeniorityLevel.Middle,
    SeniorityLevel.Senior,
    SeniorityLevel.Lead,
  ],
  category: QuestionCategory.Technical,
},
{
  text: 'How do you ensure test quality under tight deadlines?',
  type: QuestionType.VideoResponse,
  required: false,
  positionTags: [PositionTag.QA],
  seniorityLevels: [
    SeniorityLevel.Senior,
    SeniorityLevel.Lead,
  ],
  category: QuestionCategory.Leadership,
  durationInSeconds: 60,
},
];